-- Oracle 테스트 테이블 생성 스크립트
-- Oracle Database에서 실행

-- 1. 기존 테이블 삭제 (cascade constraints 사용)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEES';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DEPARTMENTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PROJECTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

-- 2. 테이블 생성
CREATE TABLE DEPARTMENTS (
    DEPARTMENTID NUMBER(10,0) PRIMARY KEY,
    DEPARTMENTNAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    BUDGET NUMBER(15,2)
)
/

CREATE TABLE EMPLOYEES (
    EMPLOYEEID NUMBER(10,0) PRIMARY KEY,
    FIRSTNAME VARCHAR2(50) NOT NULL,
    LASTNAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100),
    HIREDATE TIMESTAMP,
    SALARY NUMBER(10,2),
    ISACTIVE NUMBER(1,0)
)
/

CREATE TABLE PROJECTS (
    PROJECTID NUMBER(10,0) PRIMARY KEY,
    PROJECTNAME VARCHAR2(200) NOT NULL,
    STARTDATE DATE,
    ENDDATE DATE,
    BUDGET NUMBER(12,2),
    STATUS VARCHAR2(20)
)
/

-- 3. 시퀀스 생성 (선택 사항: auto-increment 대체)
CREATE SEQUENCE EMPLOYEES_SEQ START WITH 1 INCREMENT BY 1 /
CREATE SEQUENCE DEPARTMENTS_SEQ START WITH 1 INCREMENT BY 1 /
CREATE SEQUENCE PROJECTS_SEQ START WITH 1 INCREMENT BY 1 /

-- 4. 확인
COLUMN TABLE_NAME FORMAT A20
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN ('EMPLOYEES', 'DEPARTMENTS', 'PROJECTS');

PRINT 'Oracle 테이블 생성 완료'
